# Generated by Django 5.0.6 on 2024-06-14 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('district_name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date_created', models.DateField(default=datetime.datetime(2024, 6, 14, 5, 38, 55, 1559, tzinfo=datetime.timezone.utc))),
                ('temperature', models.JSONField(default=list)),
                ('average_temperature', models.IntegerField(null=True)),
            ],
        ),
    ]
