# Generated by Django 5.0.6 on 2024-06-14 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 5, 39, 53, 402717, tzinfo=datetime.timezone.utc)),
        ),
    ]
