# Generated by Django 5.0.6 on 2024-06-14 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_alter_temperaturedata_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 6, 5, 41, 34071, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temperaturedata',
            name='district_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
