# Generated by Django 5.0.6 on 2024-06-20 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_alter_temperaturedata_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 9, 17, 16, 16953, tzinfo=datetime.timezone.utc)),
        ),
    ]
