# Generated by Django 5.0.6 on 2024-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_alter_temperaturedata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
